### PR TITLE
corrected carecommunication graphic and moved information to intro se…

### PR DESCRIPTION
**Pull request by medcomire**
…ction

### CODE REVIEW

**Review by MedComAnders — COMMENTED** [review]
input/pagecontent/StructureDefinition-medcom-careCommunication-message-intro.md:
correction: "Please refer to the tab "Snapshort Table"  Snapshot  Table without "r"

**Comment by medcomire** [comment]
Corrected and push'ed updates plus a provenance intro page

**Comment by medcomire** [comment]
The commits are listed in the commits tab (:

**Comment by medcomire** [comment]
Have you also corrected the acknowledgement intro page - there is a conflict

**Review by MedComAnders — APPROVED** [review]

**Review by MedComAnders — APPROVED** [review]

**Comment by medcomire** [comment]
This pull request shall be deleted - a new is coming (:

**Comment by MedComAnders** [comment]
closed according to "This pull request shall be deleted - a new is coming (:"

**Pull request closed without merging**
