### PR TITLE
Version 0.8

### PR DESCRIPTION
**Pull request by ovi-medcom**

### CODE REVIEW

**Comment by jvitrifork** [comment]
Would you like me to merge it for you or are you handling this information yourself?

**Comment by jvitrifork** [comment]
@ovi-medcom @tmh-mjolner it looks like you have copied the resources from core. I would advise against doing so and instead use the https://confluence.hl7.org/pages/viewpage.action?pageId=35718627#IGPublisherDocumentation-DependencyList to add dependencies - else you'll end up in copy-paste nightmares

**Comment by ovi-medcom** [comment]
Sorry, it was me having my first experience with git. I will do my best to do it right from now :-)
/Ole

Venlig hilsen/Best regards

Ole Vilstrup Møller
Konsulent
MedCom, Forskerparken 10, 5230 Odense M
Kontor: (+45) 65 43 20 30 Mobil: (+45) 24 76 00 10
ovi@medcom.dk, medcom.dk

Advance Absence Notification (all dates inclusive)

2020.04.04-2020.04.13
2020.05.21-2020.06.01

________________________________

**Comment by jvitrifork** [comment]
@ovi-medcom still - will you be merging it yourself or do you expect me to do anything?

**Comment by ovi-medcom** [comment]
I don't want you to do anything. I will start from scratch again :-)

Venlig hilsen/Best regards

Ole Vilstrup Møller
Konsulent
MedCom, Forskerparken 10, 5230 Odense M
Kontor: (+45) 65 43 20 30 Mobil: (+45) 24 76 00 10
ovi@medcom.dk, medcom.dk

Advance Absence Notification (all dates inclusive)

2020.04.04-2020.04.13
2020.05.21-2020.06.01

________________________________

**Comment by tmh-mjolner** [comment]
> @ovi-medcom @tmh-mjolner it looks like you have copied the resources from core. I would advise against doing so and instead use the https://confluence.hl7.org/pages/viewpage.action?pageId=35718627#IGPublisherDocumentation-DependencyList to add dependencies - else you'll end up in copy-paste nightmares

I agree. I could use some guidance though on how to do it ;-)
- Where do we put the dependency list?
- How do we assemble a working profile set with all dependant resources?

**Comment by jkiddo** [comment]
Hvis du er på mødet i dag og kan deltage 10 min ekstra bagefter, så skal jeg vise det til dig

**Comment by ovi-medcom** [comment]
Perfekt, det vil jeg gerne 😊

Venlig hilsen/Best regards

Ole Vilstrup Møller
Mobil: (+45) 24 76 00 10
ovi@medcom.dk<mailto:ovi@medcom.dk>
[medcom]<https://www.medcom.dk/>


Fra: Jens Kristian Villadsen <notifications@github.com>
Sendt: 23. marts 2020 09:43
Til: hl7dk/dk-medcom-core-r4 <dk-medcom-core-r4@noreply.github.com>
Cc: Ole Vilstrup Møller <ovi@medcom.dk>; Mention <mention@noreply.github.com>
Emne: Re: [hl7dk/dk-medcom-core-r4] Version 0.8 (#1)


Hvis du er på mødet i dag og kan deltage 10 min ekstra bagefter, så skal jeg vise det til dig

**Comment by medcomire** [comment]
Jeg vil også gerne deltage..

Med venlig hilsen
Irene
21729612/ire@medcom.dk

Fra: Jens Kristian Villadsen <notifications@github.com>
Svar til: hl7dk/dk-medcom-core-r4 <reply@reply.github.com>
Dato: mandag den 23. marts 2020 kl. 09.42
Til: hl7dk/dk-medcom-core-r4 <dk-medcom-core-r4@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: Re: [hl7dk/dk-medcom-core-r4] Version 0.8 (#1)


Hvis du er på mødet i dag og kan deltage 10 min ekstra bagefter, så skal jeg vise det til dig

**Comment by tmh-mjolner** [comment]
… også gerne ;-)

**Pull request merged**
